In [1]:
!pip install pymysql

Requirement already satisfied: pymysql in c:\users\91818\anaconda3\python\lib\site-packages (1.1.2)

In [2]:
!pip install sqlalchemy

Requirement already satisfied: sqlalchemy in c:\users\91818\anaconda3\python\lib\site-packages (2.0.39)
Requirement already satisfied: greenlet!=0.4.17 in c:\users\91818\anaconda3\python\lib\site-packages (from sqlalchemy) (3.1.1)
Requirement already satisfied: typing-extensions>=4.6.0 in c:\users\91818\anaconda3\python\lib\site-packages (from sqlalchemy) (4.15.0)

In [3]:
from sqlalchemy import create_engine
import mysql.connector
import pandas as pd
engine=create_engine("mysql+pymysql://root:202020@localhost:3306/project")
df=pd.read_sql("select * from loan_data",engine)
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,Loan Date (DD/MM/YYYY)
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0,10/15/2018\r
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0,3/25/2016\r
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1,11/11/2013\r
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0,6/22/2017\r
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0,6/9/2014\r

In [25]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
 18  Loan Date       255347 non-null  object
dtypes: float64(2), int64(8), object(9)
memory usage: 37.0+ MB

In [4]:
df.describe()

,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Default
count,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000,255347.000000
mean,43.498306,82499.304597,127578.865512,574.264346,59.541976,2.501036,13.492773,36.025894,0.500212,0.116128
std,14.990258,38963.013729,70840.706142,158.903867,34.643376,1.117018,6.636443,16.969330,0.230917,0.320379
min,18.000000,15000.000000,5000.000000,300.000000,0.000000,1.000000,2.000000,12.000000,0.100000,0.000000
25%,31.000000,48825.500000,66156.000000,437.000000,30.000000,2.000000,7.770000,24.000000,0.300000,0.000000
50%,43.000000,82466.000000,127556.000000,574.000000,60.000000,2.000000,13.460000,36.000000,0.500000,0.000000
75%,56.000000,116219.000000,188985.000000,712.000000,90.000000,3.000000,19.250000,48.000000,0.700000,0.000000
max,69.000000,149999.000000,249999.000000,849.000000,119.000000,4.000000,25.000000,60.000000,0.900000,1.000000

In [27]:
df.isnull().sum()

LoanID            0
Age               0
Income            0
LoanAmount        0
CreditScore       0
MonthsEmployed    0
NumCreditLines    0
InterestRate      0
LoanTerm          0
DTIRatio          0
Education         0
EmploymentType    0
MaritalStatus     0
HasMortgage       0
HasDependents     0
LoanPurpose       0
HasCoSigner       0
Default           0
Loan Date         0
dtype: int64

### **1. Converting the  Loan Date to proper date format.**

In [5]:
df.columns=df.columns.str.replace('Loan Date (DD/MM/YYYY)','Loan Date')

In [6]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 255347 entries, 0 to 255346
Data columns (total 19 columns):
 #   Column          Non-Null Count   Dtype
---  ------          --------------   -----
 0   LoanID          255347 non-null  object
 1   Age             255347 non-null  int64
 2   Income          255347 non-null  int64
 3   LoanAmount      255347 non-null  int64
 4   CreditScore     255347 non-null  int64
 5   MonthsEmployed  255347 non-null  int64
 6   NumCreditLines  255347 non-null  int64
 7   InterestRate    255347 non-null  float64
 8   LoanTerm        255347 non-null  int64
 9   DTIRatio        255347 non-null  float64
 10  Education       255347 non-null  object
 11  EmploymentType  255347 non-null  object
 12  MaritalStatus   255347 non-null  object
 13  HasMortgage     255347 non-null  object
 14  HasDependents   255347 non-null  object
 15  LoanPurpose     255347 non-null  object
 16  HasCoSigner     255347 non-null  object
 17  Default         255347 non-null  int64
 18  Loan Date       255347 non-null  object
dtypes: float64(2), int64(8), object(9)
memory usage: 37.0+ MB

In [7]:
df.columns

Index(['LoanID', 'Age', 'Income', 'LoanAmount', 'CreditScore',
       'MonthsEmployed', 'NumCreditLines', 'InterestRate', 'LoanTerm',
       'DTIRatio', 'Education', 'EmploymentType', 'MaritalStatus',
       'HasMortgage', 'HasDependents', 'LoanPurpose', 'HasCoSigner', 'Default',
       'Loan Date'],
      dtype='object')

In [8]:
df["Loan Date"].isnull().sum()

np.int64(0)

In [9]:
df["Loan Date"]=df["Loan Date"].str.split('\r').str[0]

In [19]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,Loan Date
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0,2018-10-15
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0,2016-03-25
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1,2013-11-11
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0,2017-06-22
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0,2014-06-09

In [12]:
df["Loan Date"]=pd.to_datetime(df["Loan Date"]).dt.date

In [13]:
df.head()

,LoanID,Age,Income,LoanAmount,CreditScore,MonthsEmployed,NumCreditLines,InterestRate,LoanTerm,DTIRatio,Education,EmploymentType,MaritalStatus,HasMortgage,HasDependents,LoanPurpose,HasCoSigner,Default,Loan Date
0,I38PQUQS96,56,85994,50587,520,80,4,15.23,36,0.44,Bachelor's,Full-time,Divorced,Yes,Yes,Other,Yes,0,2018-10-15
1,HPSK72WA7R,69,50432,124440,458,15,1,4.81,60,0.68,Master's,Full-time,Married,No,No,Other,Yes,0,2016-03-25
2,C1OZ6DPJ8Y,46,84208,129188,451,26,3,21.17,24,0.31,Master's,Unemployed,Divorced,Yes,Yes,Auto,No,1,2013-11-11
3,V2KKSFM3UN,32,31713,44799,743,0,3,7.07,24,0.23,High School,Full-time,Married,No,No,Business,No,0,2017-06-22
4,EY08JDHTZP,60,20437,9139,633,8,4,6.51,48,0.73,Bachelor's,Unemployed,Divorced,No,Yes,Auto,No,0,2014-06-09

#### **2. Removing the duplicate LoanID's.**

In [14]:
df["LoanID"].isnull().sum()

np.int64(0)

In [15]:
df["LoanID"].duplicated().sum()

np.int64(0)

In [16]:
df["LoanID"].nunique()

255347

In [17]:
df.drop_duplicates(subset="LoanID",keep="first",inplace=True)

In [37]:
df[df["LoanID"].duplicated()]

Empty DataFrame
Columns: [LoanID, Age, Income, LoanAmount, CreditScore, MonthsEmployed, NumCreditLines, InterestRate, LoanTerm, DTIRatio, Education, EmploymentType, MaritalStatus, HasMortgage, HasDependents, LoanPurpose, HasCoSigner, Default, Loan Date]
Index: []

- There is no duplicated records.

#### **3. Handling missing CreditScore.**

In [45]:
df["CreditScore"].isnull().sum()

np.int64(0)

In [59]:
df.loc[(df["CreditScore"]>850) & (df["CreditScore"]<350)].shape[0]

0

In [56]:
((df["CreditScore"]>850) & (df["CreditScore"]<350)).sum()

np.int64(0)

##### There are no missng values on this dataset

#### **4. Validate negative income values.**

In [64]:
(df["Income"]<0).sum()

np.int64(0)

In [67]:
df[df["Income"]<0].shape[0]

0

##### there is no negative values.

#### **5. Standardize Yes/No columns**

In [90]:
a=[i for i in df.columns if any(df[i].isin(["Yes","No"]))]
a

['HasMortgage', 'HasDependents', 'HasCoSigner']

In [84]:
for col in a:
    print(col,"===",df[col].unique())

HasMortgage === ['Yes' 'No']
HasDependents === ['Yes' 'No']
HasCoSigner === ['Yes' 'No']

#### 
- there is all standardized values are present in the dataset so,no need to perform any operation on the dataset.

#### **6. Check invalid DTI ratios (>100%).**

In [111]:
df["DTIRatio"]=df["DTIRatio"]*100

In [114]:
(df["DTIRatio"] > 100).sum()

np.int64(0)

##### we check that there is no values present in the DTIRation or less than 100% (i.e all are (<100%) DTIRatio) .

In [116]:
df.to_sql("loan",con=engine,if_exists="replace",index=False)

255347